In [ ]:
Question No 1-      Explain different types of views. Demonstrate with suitable examples.



Ans-  In the context of databases, "views" refer to virtual tables derived from one or more base tables
      (actual physical tables) or other views. Views are useful for presenting data in a certain way without changing
      the underlying structure of the database. There are several types of views, each serving a specific purpose. 
      Let's explore some common types of views with examples:

1. **Simple Views**:
   - Simple views are based on a single table and display a subset of its columns or rows.
   - Example:
     ```sql
     CREATE VIEW EmployeeView AS
     SELECT EmployeeID, FirstName, LastName
     FROM Employees
     WHERE Department = 'IT';
     ```
   - This view displays only the ID, first name, and last name of employees working in the IT department.

2. **Complex Views**:
   - Complex views involve multiple tables and often include joins or aggregations.
   - Example:
     ```sql
     CREATE VIEW SalesSummary AS
     SELECT p.ProductName, SUM(s.Quantity) AS TotalSold
     FROM Products p
     INNER JOIN Sales s ON p.ProductID = s.ProductID
     GROUP BY p.ProductName;
     ```
   - This view summarizes total sales for each product by joining the Products and Sales tables.

3. **Indexed Views**:
   - Indexed views are stored physically in the database and can have indexes, improving query performance.
   - Example:
     ```sql
     CREATE VIEW IndexedSalesSummary
     WITH SCHEMABINDING
     AS
     SELECT p.ProductName, SUM(s.Quantity) AS TotalSold
     FROM dbo.Products p
     INNER JOIN dbo.Sales s ON p.ProductID = s.ProductID
     GROUP BY p.ProductName;
     
     CREATE UNIQUE CLUSTERED INDEX IX_IndexedSalesSummary_ProductName 
     ON IndexedSalesSummary (ProductName);
     ```
   - This view is similar to the previous example but is indexed for faster retrieval.

4. **Materialized Views**:
   - Materialized views store the result set of the query physically, allowing for faster access at the cost of
     storage and maintenance overhead.
   - Example:
     ```sql
     CREATE MATERIALIZED VIEW MonthlySales AS
     SELECT DATE_FORMAT(OrderDate, '%Y-%m') AS Month, SUM(TotalAmount) AS Total
     FROM Orders
     GROUP BY DATE_FORMAT(OrderDate, '%Y-%m');
     ```
   - This view stores the total sales for each month, computed from the Orders table.

5. **Recursive Views**:
   - Recursive views are used for recursive queries, typically involving hierarchical data structures like
     organizational charts.
   - Example:
     ```sql
     CREATE VIEW EmployeeHierarchy AS
     SELECT EmployeeID, FirstName, LastName, ManagerID
     FROM Employees
     WHERE ManagerID IS NULL
     UNION ALL
     SELECT e.EmployeeID, e.FirstName, e.LastName, e.ManagerID
     FROM Employees e
     INNER JOIN EmployeeHierarchy eh ON e.ManagerID = eh.EmployeeID;
     ```
   - This view retrieves an organizational hierarchy where each employee reports to another employee, forming a
     tree-like structure.

Each type of view serves a distinct purpose and can be used based on the specific requirements of the database and application.





Question No 2-      What is the difference between function and stored procedure? Write syntax for creating 
                    functions and stored procedures.


    
Ans-

      In the context of databases, functions and stored procedures are both stored blocks of SQL code that can be 
    invoked to perform specific tasks. However, they have some key differences in terms of their purpose, usage, and syntax.

**Differences between Functions and Stored Procedures:**

1. **Return Value**:
   - Functions must return a single value.
   - Stored procedures may or may not return values.

2. **Usage**:
   - Functions are typically used to compute and return scalar values or table-based results.
   - Stored procedures are generally used to perform operations such as data manipulation, transaction control, or business
     logic processing.

3. **Transaction Control**:
   - Functions cannot contain transaction control statements like COMMIT or ROLLBACK.
   - Stored procedures can contain transaction control statements.

4. **Scope**:
   - Functions can be used in SQL queries, such as in the SELECT statement.
   - Stored procedures cannot be used in SQL queries directly; they are invoked using EXECUTE or CALL statements.

5. **Error Handling**:
   - Functions can handle errors using TRY-CATCH blocks but cannot raise errors using RAISEERROR.
   - Stored procedures can handle errors using TRY-CATCH blocks and can raise custom errors using RAISEERROR.

**Syntax for Creating Functions:**
```sql
CREATE FUNCTION function_name (parameters)
RETURNS return_data_type
AS
BEGIN
    -- Function body
    RETURN return_value;
END;
```

**Example:**
```sql
CREATE FUNCTION GetEmployeeCount ()
RETURNS INT
AS
BEGIN
    DECLARE @Count INT;
    SELECT @Count = COUNT(*) FROM Employees;
    RETURN @Count;
END;
```

**Syntax for Creating Stored Procedures:**
```sql
CREATE PROCEDURE procedure_name (parameters)
AS
BEGIN
    -- Procedure body
END;
```

**Example:**
```sql
CREATE PROCEDURE UpdateEmployeeSalary @EmployeeID INT, @NewSalary DECIMAL
AS
BEGIN
    UPDATE Employees
    SET Salary = @NewSalary
    WHERE EmployeeID = @EmployeeID;
END;
```

In summary, functions are primarily used for calculations and returning values, while stored procedures are used
for executing a sequence of SQL statements or performing specific operations. The choice between using a function
or a stored procedure depends on the specific requirements of the task at hand.


Question No 3-      What is an index in SQL? What are the different types of indexes in SQL? 



Ans-

 
    In SQL databases, an index is a data structure that provides quick access to rows in a table based on the values
    of one or more columns. Indexes are used to speed up data retrieval operations, such as SELECT queries, by 
    allowing the database engine to locate rows more efficiently.

There are several types of indexes commonly used in SQL databases:

1. **Single-Column Index**:
   - A single-column index is created on a single column of a table.
   - It speeds up queries that filter or sort data based on that column.
   - Example:
     ```sql
     CREATE INDEX idx_last_name ON employees(last_name);
     ```

2. **Composite Index**:
   - A composite index is created on multiple columns of a table.
   - It can speed up queries that filter or sort data based on combinations of these columns.
   - Example:
     ```sql
     CREATE INDEX idx_last_name_first_name ON employees(last_name, first_name);
     ```

3. **Unique Index**:
   - A unique index ensures that all values in the indexed columns are unique.
   - It is commonly used to enforce uniqueness constraints on columns.
   - Example:
     ```sql
     CREATE UNIQUE INDEX idx_employee_id ON employees(employee_id);
     ```

4. **Clustered Index**:
   - A clustered index determines the physical order of rows in a table.
   - Each table can have only one clustered index because the rows are physically ordered by the clustered index key.
   - Example:
     ```sql
     CREATE CLUSTERED INDEX idx_employee_id ON employees(employee_id);
     ```

5. **Non-Clustered Index**:
   - A non-clustered index is a separate structure from the table and contains a sorted list of references to the table's rows.
   - It does not affect the physical order of rows in the table.
   - Example:
     ```sql
     CREATE NONCLUSTERED INDEX idx_last_name ON employees(last_name);
     ```

6. **Full-Text Index**:
   - A full-text index is used for searching text data efficiently.
   - It allows for advanced text searching capabilities, such as searching for words or phrases, word proximity searches, 
     and stemming.
   - Example:
     ```sql
     CREATE FULLTEXT INDEX idx_description ON products(description);
     ```

7. **Spatial Index**:
   - A spatial index is used for optimizing spatial queries on spatial data types, such as geometry and geography.
   - It enables efficient searching and analysis of spatial data.
   - Example:
     ```sql
     CREATE SPATIAL INDEX idx_location ON locations(geometry_column);
     ```

These are some of the commonly used types of indexes in SQL databases, each serving a specific purpose in optimizing 
data retrieval performance. The choice of index type depends on the nature of the data, the types of queries performed, 
and the overall database design considerations.
    

    
    
Question No 4-      Showcase an example of exception handling in SQL stored procedure.



Ans-


  Certainly! Below is an example of a SQL stored procedure that demonstrates exception handling using the TRY-CATCH block:

  ```sql
  CREATE PROCEDURE DivideNumbers
    @Numerator INT,
    @Denominator INT
 AS
 BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        DECLARE @Result DECIMAL(18, 2);

        -- Check if the denominator is zero
        IF @Denominator = 0
        BEGIN
            THROW 50001, 'Division by zero is not allowed.', 1;
        END

        -- Perform the division
        SET @Result = @Numerator / CAST(@Denominator AS DECIMAL(18, 2));

        -- Output the result
        SELECT @Result AS Result;
    END TRY
    BEGIN CATCH
        -- Handle the exception
        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();

        -- Log the error message
        INSERT INTO ErrorLog (ErrorMessage, ErrorSeverity, ErrorState)
        VALUES (@ErrorMessage, @ErrorSeverity, @ErrorState);

        -- Raise the error to the caller
        RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
END;
```

In this stored procedure:

- We first define the procedure `DivideNumbers` which takes two parameters: `@Numerator` and `@Denominator`.
- Inside the `BEGIN TRY` block, we attempt to perform the division of `@Numerator` by `@Denominator`.
- We first check if the `@Denominator` is zero, which would result in a division by zero error. In that case, 
  we use the `THROW` statement to raise a custom error with a specific error code, message, and state.
- If the division is successful, we calculate the result and output it using a `SELECT` statement.
- In the `BEGIN CATCH` block, we catch any errors that occur within the `TRY` block.
- We retrieve the error message, severity, and state using the `ERROR_MESSAGE()`, `ERROR_SEVERITY()`, and `ERROR_STATE()
  ` functions, respectively.
- We log the error message, severity, and state into an `ErrorLog` table for later analysis or debugging.
- Finally, we use the `RAISERROR` statement to re-raise the error to the caller, which will handle the error 
  appropriately based on the error message, severity, and state.

This example demonstrates how to handle exceptions within a SQL Server stored procedure using the TRY-CATCH block
to gracefully handle errors and provide meaningful error messages for better troubleshooting.



Question No 5-      Create a SQL function to split strings into rows on a given character? 
                    Input String: Stephen;peter;berry;Olivier;caroline;
                    Stephen
                    Peter
                    Berry
                    Oliver
                    Caroline




Ans-




To create a SQL function to split strings into rows based on a given character, you can use a combination of string
manipulation functions and a table-valued function. Below is an example of how you can achieve this in SQL Server:

```sql
CREATE FUNCTION dbo.SplitStringIntoRows
(
    @InputString NVARCHAR(MAX),
    @Delimiter CHAR(1)
)
RETURNS @OutputTable TABLE (SplitValue NVARCHAR(MAX))
AS
BEGIN
    DECLARE @StartPosition INT = 1;
    DECLARE @EndPosition INT;
    
    -- Loop until all delimiters are processed
    WHILE @StartPosition <= LEN(@InputString)
    BEGIN
        -- Find the position of the next delimiter
        SET @EndPosition = CHARINDEX(@Delimiter, @InputString, @StartPosition);
        
        -- If delimiter not found, set the end position to the length of the string
        IF @EndPosition = 0
        BEGIN
            SET @EndPosition = LEN(@InputString) + 1;
        END
        
        -- Extract the substring between the start and end positions
        INSERT INTO @OutputTable (SplitValue)
        VALUES (SUBSTRING(@InputString, @StartPosition, @EndPosition - @StartPosition));
        
        -- Move the start position to the next character after the delimiter
        SET @StartPosition = @EndPosition + 1;
    END
    
    RETURN;
END;
```

You can use this function to split the input string into rows based on the ';' character:

```sql
DECLARE @InputString NVARCHAR(MAX) = 'Stephen;peter;berry;Olivier;caroline;';
SELECT SplitValue
FROM dbo.SplitStringIntoRows(@InputString, ';');
```

This will return the following result:

```
SplitValue
-----------
Stephen
peter
berry
Olivier
caroline
```

Explanation:
- The function `dbo.SplitStringIntoRows` takes two parameters: `@InputString` (the input string to be split) and
    `@Delimiter` (the character used to split the string).
- Within the function, a table variable `@OutputTable` is declared to store the split values.
- The function then iterates through the input string, finding the positions of the delimiters and extracting
substrings between them.
- Each substring is inserted into the `@OutputTable`.
- Finally, the function returns the `@OutputTable`, which contains the split values.







Question No 6-     What is a temporary and a variable table? Write suitable syntax to create temporary tables and 
                   variable tables.


    
    
Ans-

In SQL, temporary tables and table variables serve similar purposes in that they both allow you to store and manipulate
data temporarily within a session. However, there are some differences in terms of their scope, behavior, and usage.

**Temporary Tables:**

Temporary tables are physical tables that are stored in the tempdb system database. They are useful for storing 
intermediate results or temporary data that needs to persist across multiple sessions within the same connection or session.

**Syntax for Creating Temporary Tables:**

```sql
CREATE TABLE #TempTableName (
    Column1 DataType1,
    Column2 DataType2,
    ...
);
```

Example:
```sql
CREATE TABLE #TempEmployees (
    EmployeeID INT,
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50)
);
```

**Table Variables:**

Table variables are variables of type TABLE that can hold a set of records similar to a temporary table. However, 
table variables are stored in memory and exist only for the duration of the batch, procedure, or function in which
they are declared. They are useful for smaller datasets and do not have as much overhead as temporary tables.

**Syntax for Creating Table Variables:**

```sql
DECLARE @TableVariableName TABLE (
    Column1 DataType1,
    Column2 DataType2,
    ...
);
```

Example:
```sql
DECLARE @Employees TABLE (
    EmployeeID INT,
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50)
);
```

**Comparison:**

- Temporary tables are physically stored in the tempdb database and can be accessed across multiple sessions within
the same connection, while table variables are stored in memory and have a limited scope within the batch, procedure,
or function where they are declared.
- Temporary tables can be indexed and used with transactions, while table variables cannot be indexed and do not
support transactions.
- Temporary tables have higher overhead due to disk I/O operations and logging in the tempdb database, while table
variables have lower overhead as they are stored in memory.

In summary, both temporary tables and table variables serve as temporary storage mechanisms in SQL, but the choice 
between them depends on factors such as data size, scope, and performance considerations.